Repository CA-G12/kitty-facts, pull requests merged in 2022-08, with the labels that each got.

#8 Creating file structure
  .gitignore
  index.html
  js/dom.js
  js/fetchOperations.js
  js/logic.js
  style.css
  tests/test.js
Labels: done, merged

#11 added loadCataas function
  js/fetchOperations.js
Labels: done, merged

#13 creat xhr request
  js/fetchOperations.js
Labels: merged

#15 Refactor xhr requests
  index.html
  js/dom.js
  js/fetchOperations.js
  style.css
Labels: done, merged

#17 Randomize id for the pic
  js/dom.js
  js/logic.js
Labels: awaiting review, bugfix

#22 Styling webpage
  index.html
  js/dom.js
  js/fetchOperations.js
  style.css
Labels: done, pair programming task

#30 last touchups and fixing merge errors
  index.html
  js/dom.js
  style.css
Labels: awaiting review, bugfix
